language: python

addons:
  postgresql: "9.3"

python:
    - "2.7"
    - "3.5"

virtualenv:
  system_site_packages: true

env:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

cache:
  apt: true
  directories:
     - $HOME/.pip_download_cache

install:
    - pip install nose==1.3.1 psycopg2==2.5.3 SQLAlchemy==0.9.4

before_script:
  - psql -c 'create database eradate_test;' -U postgres

script: nosetests

notifications:
    hipchat: 7ee7585eab87a19ce0eee5b6173707@Back-End
